name: Release

on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write       
      issues: write        # Required to create issues (for semantic release to update issues)
      pull-requests: write # Required to interact with pull requests (for semantic release to create changelogs)
      actions: write       # Required for creating releases and interacting with GitHub actions
      deployments: write   # Required for creating deployments (if you're deploying the code)
    
    steps:
      - name: Set Timezone to Brisbane (UTC+10)
        uses: MathRobin/timezone-action@v1.1
        with:
            timezoneLinux: 'Australia/Brisbane'
            timezoneMacos: 'Australia/Brisbane'
            timezoneWindows: 'Australia/Brisbane'
          
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'  # Specify the version of Node.js you're using

      - name: Install dependencies
        run: npm install
        
      - name: Adjust Date for Release Notes
        run: |
          export RELEASE_DATE=$(TZ="Australia/Brisbane" date +"%Y-%m-%d")
          echo "Release Date: $RELEASE_DATE"

      - name: Run Semantic Release
        env:
          TZ: Australia/Brisbane
          RELEASE_DATE: ${{ steps.adjust_date.outputs.RELEASE_DATE }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token with proper permissions
        run: npx semantic-release
        
      - name: Adjust Changelog Date
        run: |
          export RELEASE_DATE=$(TZ="Australia/Brisbane" date +"%Y-%m-%d")
          echo "Updating changelog with release date: $RELEASE_DATE"
          sed -i 's/\(## \[.*\] - \)[0-9]*-[0-9]*-[0-9]*/\1'"$RELEASE_DATE"'/' CHANGELOG.md
