name: Release

on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write       
      issues: write        # Required to create issues (for semantic release to update issues)
      pull-requests: write # Required to interact with pull requests (for semantic release to create changelogs)
      actions: write       # Required for creating releases and interacting with GitHub actions
      deployments: write   # Required for creating deployments (if you're deploying the code)
    
    steps:         
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'  # Specify the version of Node.js you're using

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token with proper permissions
        run: npx semantic-release
        
      - name: Set Git user identity
        run: |
          git config --global user.email "corey.wells@edge2020.com.au"
          git config --global user.name "Corey Wells"
          
      - name: Adjust Changelog Date Format
        run: |
          echo "Adjusting changelog date format..."

          # Export custom date format (e.g., Brisbane time)
          export NEW_DATE=$(TZ="Australia/Brisbane" date +"%Y-%m-%d")
          echo "New release date: $NEW_DATE"

          # Modify CHANGELOG.md and replace dates
          sed -i "0,/## /s/\([0-9]*-[0-9]*-[0-9]*\)/$NEW_DATE/" CHANGELOG.md

          # Commit the updated changelog back to the repository
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog with Brisbane date format [skip ci]"
          git push 