name: Release

on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write       
      issues: write        # Required to create issues (for semantic release to update issues)
      pull-requests: write # Required to interact with pull requests (for semantic release to create changelogs)
      actions: write       # Required for creating releases and interacting with GitHub actions
      deployments: write   # Required for creating deployments (if you're deploying the code)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.1'  # Specify the version of Node.js you're using

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token with proper permissions
        run: npx semantic-release
